EXAMPLE_REQUESTS = {
    "example_1": {
        "query": "Malbec e posicionamento de marca",
        "objective": "Criar um artigo curto de marketing para blog sobre a linha Malbec. Coloque os preços também",
        "filter_search": {"collection_id": ["oboticario"]},
        "content_count": 5,
        "body_min_chars": 700,
        "body_max_chars": 1200,
        "max_results": 5,
        "extra_requirements": "Tom premium, linguagem persuasiva e CTA no final. Mencione os produtos da O Boticário",
    },
    "example_2": {
        "query": "Cuidados com a pele no inverno",
        "objective": "Gerar um post de Instagram para a linha de cuidados com a pele da O Boticário, focando em dicas para o inverno. Inclua um CTA para visitar a loja online.",
        "filter_search": {"collection_id": ["oboticario"]},
        "content_count": 5,
        "body_min_chars": 700,
        "body_max_chars": 1200,
        "max_results": 25,
        "extra_requirements": "Tom amigável e informativo, use emojis relacionados ao inverno e cuidados com a pele. Mencione os produtos da O Boticário",
    },
    "example_3": {
        "query": "Perfumes masculinos e tendências de mercado",
        "objective": "Criar um artigo de blog focado em tendências de mercado para perfumes masculinos, destacando os produtos da linha Malbec. Inclua informações sobre notas olfativas e sugestões de uso.",
        "filter_search": {"collection_id": ["oboticario"]},
        "content_count": 5,
        "body_min_chars": 700,
        "body_max_chars": 1200,
        "max_results": 5,
        "extra_requirements": "Tom sofisticado e informativo, com foco em público masculino adulto. Mencione os produtos da O Boticário",
    },
    "example_4": {
        "query": "Lançamentos de maquiagem e dicas de aplicação",
        "objective": "Gerar um post para Instagram sobre os lançamentos de maquiagem da O Boticário, incluindo dicas de aplicação e sugestões de produtos para diferentes tipos de pele.",
        "filter_search": {"collection_id": ["oboticario"]},
        "content_count": 5,
        "body_min_chars": 700,
        "body_max_chars": 1200,
        "max_results": 5,
        "extra_requirements": "Tom descontraído e acessível, com foco em público jovem adulto. Use emojis relacionados à maquiagem. Mencione os produtos da O Boticário",
    },
    "example_5": {
        "query": "Estimula a produção de colágeno",
        "objective": "Criar um post para Instagram sobre produtos que estimulam a produção de colágeno, destacando os benefícios para a pele e sugestões de uso.",
        "filter_search": {"collection_id": ["oboticario"]},
        "content_count": 5,
        "body_min_chars": 700,
        "body_max_chars": 1200,
        "max_results": 5,
        "extra_requirements": "Tom informativo e confiável, com foco em público adulto interessado em cuidados com a pele. Mencione os produtos da O Boticário que possuem essa função e use emojis relacionados a cuidados com a pele.",
    },

}